language: node_js
sudo: false
node_js:
  - 9
install:
  - yarn
script:
  - yarn tslint
  - yarn build
cache: yarn
before_deploy:
  - openssl aes-256-cbc -K $encrypted_8d7484616f6a_key -iv $encrypted_8d7484616f6a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - buttplug.world
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after index.html dist/build.js buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world/playground
  on:
    branch: master
